version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    SOURCE_LOCATION: "https://github.com/umihico/blog.git"

phases:
  build:
    commands:
      - terragrunt apply -auto-approve --terragrunt-working-dir terraform/environments/cicd
      - |
        if [ "${CODEBUILD_WEBHOOK_TRIGGER#branch/}" == "development" ]; then
          terragrunt apply -auto-approve --terragrunt-working-dir terraform/environments/dev
        fi
      - |
        if [ "${CODEBUILD_WEBHOOK_TRIGGER#branch/}" == "main" ]; then
          terragrunt apply -auto-approve --terragrunt-working-dir terraform/environments/prod
        fi
