version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    SOURCE_LOCATION: "https://github.com/umihico/blog.git"

phases:
  build:
    commands:
      - terragrunt apply -auto-approve
