version: 0.2

env:
  variables:
    GITHUB_REPOSITORY_OWNER_NAME: "umihico"
    GITHUB_REPOSITORY_NAME: "blog"
    AWS_DEFAULT_REGION: "ap-northeast-1"
    SOURCE_LOCATION: "https://github.com/umihico/blog.git"
    PROD_DOMAIN: "umihi.co"
    DEV_DOMAIN: "dev-blog.umihi.co"

phases:
  build:
    commands:
      - terragrunt apply -auto-approve

cache:
  paths:
    - "next/node_modules/**/*"
    - "next/.next/cache/**/*"
