version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    SOURCE_LOCATION: "https://github.com/umihico/blog.git"

phases:
  build:
    commands:
      - terragrunt apply -auto-approve
      - |
        cd next
        aws s3 sync s3://${SLS_CACHE_BUCKET}/.serverless .serverless --delete # create empty directory without errors when the directory does not exist
        npm install
        components-v1
        aws s3 sync .serverless s3://${SLS_CACHE_BUCKET}/.serverless --delete
