version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    SOURCE_LOCATION: "https://github.com/umihico/blog.git"
    PROD_DOMAIN: "umihi.co"
    DEV_DOMAIN: "dev-blog.umihi.co"

phases:
  build:
    commands:
      - terragrunt apply -auto-approve
      - |
        cd next
        npm install
        npm run export
        aws s3 sync out s3://${SLS_ASSET_BUCKET} --delete
