version: "3"
services:
  npm:
    image: node
    working_dir: /usr/src/app
    volumes:
      - ./next:/usr/src/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_GITHUB_URL: ${NEXT_PUBLIC_GITHUB_URL:-https://example.com/}
      NEXT_PUBLIC_BLOG_TITLE: ${NEXT_PUBLIC_BLOG_TITLE:-My Awsome Blog}
      NEXT_PUBLIC_BLOG_DESCRIPTION: ${NEXT_PUBLIC_BLOG_DESCRIPTION:-My Awsome Blog Description comes here.}
