version: "3"
services:
  npm:
    image: node
    working_dir: /usr/src/app
    volumes:
      - ./next:/usr/src/app
      - ./posts:/usr/src/posts
    command: npm run dev
    ports:
      - "${LOCALHOST_NEXTJS_PORT:-3000}:3000"
    environment:
      NEXT_PUBLIC_GITHUB_URL: ${NEXT_PUBLIC_GITHUB_URL:-https://example.com/}
      NEXT_PUBLIC_BLOG_TITLE: ${NEXT_PUBLIC_BLOG_TITLE:-My Awsome Blog}
      NEXT_PUBLIC_GTM_ID: ${NEXT_PUBLIC_GTM_ID}
      NEXT_PUBLIC_BLOG_DESCRIPTION: ${NEXT_PUBLIC_BLOG_DESCRIPTION:-My Awsome Blog Description comes here.}
      NEXT_PUBLIC_HOST_NAME: ${NEXT_PUBLIC_HOST_NAME:-https://og-image.vercel.app/Next.js-Blog-Starter-Example.png}
