name: git-pr-release
on:
  push:
    branches:
      - development

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    env:
      GIT_PR_RELEASE_BRANCH_STAGING: development
      GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - uses: ruby/setup-ruby@v1
      - run: gem install --no-document git-pr-release
      - run: git-pr-release
        env:
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
